"""
武将数据库 —— 唯一的武将数据源
修改武将数值、添加新武将都在这个文件中操作，无需改动任何其他文件

字段说明：
  id          武将唯一ID
  name        中文名
  camp        阵营: 蜀/魏/吴/他
  rarity      稀有度: COMMON/RARE/EPIC/LEGENDARY（对应费用: 1.0/1.5/2.0/3.0）
  cost        费用
  force       武力 (影响普攻伤害)
  intelligence 智力 (影响策略伤害)
  attributes  属性列表: 勇猛/魅力/募兵/防栅/连环/复活/伏兵 (空列表=无属性)
  skill_id    主动技能ID (skills_config.py 中定义)
  image_file  武将卡图片文件名 (存放在 assets/images/generals/)
  biography   武将生平简介（展示页面用）
"""

GENERALS_DATA = [
    # ==================== 蜀 ====================
    {
        "id": 2001,
        "name": "刘备",
        "camp": "蜀",
        "rarity": "RARE",
        "cost": 1.5,
        "force": 5,
        "intelligence": 7,
        "attributes": ["魅力"],
        "skill_id": "rally",
        "image_file": "liu_bei.png",
        "biography": "字玄德，蜀汉开国皇帝。以仁德著称，与关羽、张飞桃园结义，三顾茅庐请诸葛亮出山，建立蜀汉政权。",
    },
    {
        "id": 2002,
        "name": "关羽",
        "camp": "蜀",
        "rarity": "EPIC",
        "cost": 2.0,
        "force": 9,
        "intelligence": 5,
        "attributes": ["勇猛"],
        "skill_id": "fierce_attack",
        "image_file": "guan_yu.png",
        "biography": "字云长，蜀汉五虎上将之首。温酒斩华雄，过五关斩六将，水淹七军威震华夏。以忠义闻名，被尊为武圣。",
    },
    {
        "id": 2003,
        "name": "张飞",
        "camp": "蜀",
        "rarity": "EPIC",
        "cost": 2.0,
        "force": 10,
        "intelligence": 3,
        "attributes": ["勇猛"],
        "skill_id": "fierce_attack",
        "image_file": "zhang_fei.png",
        "biography": "字翼德，蜀汉五虎上将。长坂坡一声断喝退曹军，勇猛无双。与刘备、关羽桃园结义，情深义重。",
    },
    {
        "id": 2004,
        "name": "赵云",
        "camp": "蜀",
        "rarity": "RARE",
        "cost": 1.5,
        "force": 8,
        "intelligence": 6,
        "attributes": ["伏兵"],
        "skill_id": "strength_tactics",
        "image_file": "zhao_yun.png",
        "biography": "字子龙，蜀汉五虎上将。长坂坡单骑救阿斗，一身是胆。征战一生未尝败绩，被誉为常胜将军。",
    },
    {
        "id": 2005,
        "name": "诸葛亮",
        "camp": "蜀",
        "rarity": "LEGENDARY",
        "cost": 3.0,
        "force": 3,
        "intelligence": 10,
        "attributes": ["连环"],
        "skill_id": "fire_attack",
        "image_file": "zhuge_liang.png",
        "biography": "字孔明，号卧龙，蜀汉丞相。隆中对定三分天下，出师表千古流传。用兵如神，发明木牛流马、诸葛连弩。",
    },

    # ==================== 魏 ====================
    {
        "id": 3001,
        "name": "曹操",
        "camp": "魏",
        "rarity": "LEGENDARY",
        "cost": 3.0,
        "force": 7,
        "intelligence": 9,
        "attributes": ["魅力"],
        "skill_id": "rally",
        "image_file": "cao_cao.png",
        "biography": "字孟德，曹魏政权的奠基人。挟天子以令诸侯，统一北方。文武兼备，著有《短歌行》，兵法谋略冠绝当世。",
    },
    {
        "id": 3002,
        "name": "夏侯惇",
        "camp": "魏",
        "rarity": "RARE",
        "cost": 1.5,
        "force": 8,
        "intelligence": 5,
        "attributes": ["勇猛"],
        "skill_id": "strength_tactics",
        "image_file": "xiahou_dun.png",
        "biography": "字元让，曹魏大将。拔矢啖睛，悍勇无匹。为曹操族弟，深得信任，官至大将军。",
    },
    {
        "id": 3003,
        "name": "张辽",
        "camp": "魏",
        "rarity": "RARE",
        "cost": 1.5,
        "force": 8,
        "intelligence": 7,
        "attributes": ["募兵"],
        "skill_id": "fierce_attack",
        "image_file": "zhang_liao.png",
        "biography": "字文远，曹魏五子良将之首。合肥之战以八百破十万，威震逍遥津，江东小儿闻其名不敢夜啼。",
    },
    {
        "id": 3004,
        "name": "司马懿",
        "camp": "魏",
        "rarity": "EPIC",
        "cost": 2.0,
        "force": 4,
        "intelligence": 9,
        "attributes": ["伏兵"],
        "skill_id": "intimidate",
        "image_file": "sima_yi.png",
        "biography": "字仲达，曹魏重臣。善用兵，多次抵御诸葛亮北伐。深谋远虑，隐忍多年，终为司马氏篡魏奠基。",
    },

    # ==================== 吴 ====================
    {
        "id": 4001,
        "name": "孙坚",
        "camp": "吴",
        "rarity": "RARE",
        "cost": 1.5,
        "force": 7,
        "intelligence": 6,
        "attributes": ["复活"],
        "skill_id": "strength_tactics",
        "image_file": "sun_jian.png",
        "biography": "字文台，东吴奠基人。勇猛刚毅，讨伐董卓时率先攻入洛阳。获传国玉玺，为孙吴霸业之始。",
    },
    {
        "id": 4002,
        "name": "周瑜",
        "camp": "吴",
        "rarity": "EPIC",
        "cost": 2.0,
        "force": 5,
        "intelligence": 9,
        "attributes": ["连环"],
        "skill_id": "fire_attack",
        "image_file": "zhou_yu.png",
        "biography": "字公瑾，东吴大都督。赤壁之战火烧曹营，谈笑间樯橹灰飞烟灭。精通音律，曲有误周郎顾。",
    },
    {
        "id": 4003,
        "name": "甘宁",
        "camp": "吴",
        "rarity": "RARE",
        "cost": 1.5,
        "force": 9,
        "intelligence": 4,
        "attributes": ["募兵"],
        "skill_id": "fierce_attack",
        "image_file": "gan_ning.png",
        "biography": "字兴霸，东吴虎将。原为锦帆贼，后投孙权。百骑劫曹营，勇冠三军，孙权赞曰「孟德有张辽，孤有甘兴霸」。",
    },

    # ==================== 他 ====================
    {
        "id": 1001,
        "name": "张任",
        "camp": "他",
        "rarity": "COMMON",
        "cost": 1.0,
        "force": 6,
        "intelligence": 6,
        "attributes": ["伏兵"],
        "skill_id": "strength_tactics",
        "image_file": "zhang_ren.png",
        "biography": "益州名将，刘璋部将。以伏兵战术闻名，落凤坡设伏射杀庞统。被俘后宁死不降，以忠烈著称。",
    },
    {
        "id": 5001,
        "name": "吕布",
        "camp": "他",
        "rarity": "LEGENDARY",
        "cost": 3.0,
        "force": 10,
        "intelligence": 2,
        "attributes": ["勇猛"],
        "skill_id": "fierce_attack",
        "image_file": "lv_bu.png",
        "biography": "字奉先，三国第一猛将。人中吕布，马中赤兔。辕门射戟显神威，虎牢关前战三英。性情无常，终为曹操所擒杀。",
    },
    {
        "id": 1003,
        "name": "鲁肃",
        "camp": "吴",
        "rarity": "RARE",
        "cost": 1.5,
        "force": 4,
        "intelligence": 8,
        "attributes": ["防栅"],
        "skill_id": "alliance_pact",
        "image_file": "lu_su.png",
        "biography": "字子敬，东吴谋主。主张联刘抗曹，促成赤壁之战孙刘联盟。为人忠厚，见识卓越，继周瑜后都督江东军事。",
    },
]
